### ISSUE TITLE
link is dead: https://platform-docs.cloud.paas.psi.redhat.com/backend/rbac.html

### ISSUE THREAD

**Issue by petli-openshift** [RedHatInsights/rbac-config#237]
I followed that link and the page displayed - "Application is not available".

**Comment by romanblanco** [comment]
@astrozzc, would you know where to find the current link?

**Comment by astrozzc** [comment]
@romanblanco @petli-openshift I am not sure what the link was, but here you could find the docs of rbac: https://consoledot.pages.redhat.com/docs/dev/services/rbac.html
